class AppConstants:
    CODE_OK = 200
    CODE_INVALID_REQUEST = 400
    CODE_UNAUTHORISED = 401
    CODE_FORBIDDEN = 403
    CODE_INTERNAL_SERVER_ERROR = 500
    CODE_NOT_IMPLEMENTED = 501
    CODE_BAD_GATEWAY = 502
    CODE_SERVICE_UNAVAILABLE = 503
    CODE_GATEWAY_TIMEOUT = 504
    SUCCESSFULL_STATUS_CODE = "200"
    UNSUCCESSFULL_STATUS_CODE= "500"

